#!/bin/bash

#validate yaml
/bbx/bin/biobox-validator/validate-biobox-file --schema=/bbx/schema/schema.yaml --input=/bbx/input/biobox.yaml

#if valid yaml run ray command
if [ $? -eq  0 ]
then	
	python /bbx/bin/command_handler.py -i /bbx/input/biobox.yaml -o /bbx/output
else
    exit 1;
fi
