---
type: "//rec"
required: 
    version: "//str"
    arguments: 
      type: "//arr"
      length: 
        min: 1
      contents: 
        type: "//any"
        of: 
          - 
            type: "//rec"
            required: 
              fastq: 
                type: "//arr"
                contents: 
                  type: "//rec"
                  required: 
                    path: "//str"
                    id: "//str"
                    type: 
                      type: "//any"
                      of: 
                        - 
                          type: "//str"
                          value: "paired"
                        - 
                          type: "//str"
                          value: "single"
                length: 
                  min: 1
          - 
            type: "//rec"
            required: 
              fragment_size: 
                type: "//arr"
                contents: 
                  type: "//rec"
                  required: 
                    id: "//str"
                    value: "//num"
                length: 
                  min: 1
