---
  type: "//rec"
  required: 
    version: "//str"
    arguments: 
      type: "//rec"
      required: 
        fastq: 
          type: "//arr"
          contents: 
            type: "//rec"
            required: 
              path: "//str"
              id: "//str"
              type: 
                type: "//any"
                of: 
                  - 
                    type: "//str"
                    value: "paired"
                  - 
                    type: "//str"
                    value: "single"
      optional: 
        fragment_size: 
          type: "//arr"
          contents: 
            type: "//rec"
            required: 
              id: "//str"
              value: "//num"
